\echo
\echo Creating Fishbase/Sealifebase Databases...
\echo

DROP DATABASE IF EXISTS fbapp;
CREATE DATABASE fbapp;
DROP DATABASE IF EXISTS sealife;
CREATE DATABASE sealife;

DROP USER IF EXISTS fishbase;
CREATE USER fishbase WITH PASSWORD 'fishbase';
DROP USER IF EXISTS web_fb;
CREATE USER web_fb WITH PASSWORD 'web_fb' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION;

ALTER DATABASE fbapp OWNER TO fishbase;
ALTER DATABASE sealife OWNER TO fishbase;

GRANT postgres TO fishbase;
