#!/bin/sh
#set -x

DATABASE_NAME=fishbase

###########################################################
## Function to call when error is encountered
###########################################################
ExitWithError () {
  echo
  echo #####
  echo Error encountered trying to create ${DATABASE_NAME} db.
  echo See ./log/$SQLINPUTFILE.log for more details...
  echo #####
  SQLINPUTFILE=
  exit 1            
}

###########################################################
## Process command line parameter(s)
###########################################################
if [ -z "$1" ]; then
  DbHost=localhost
else
  DbHost=$1
fi

if [ -z "$2" ]; then
  DbPort=5432
else
  DbPort=$2
fi

if [ -z "$3" ]; then
  RestoreThreadCount=8
else
  RestoreThreadCount=$3
fi

###########################################################
## Deleting any previous log files
###########################################################
if [ ! -d log ]; then
  mkdir log
fi                                                          

rm -f log/*.log

PSQL="psql -U postgres -h $DbHost -p $DbPort"
PSQLFISHBASE="psql -U fishbase -h $DbHost -p $DbPort"
RESTORE="pg_restore -h $DbHost -p $DbPort -Fc -a -j $RestoreThreadCount"

###########################################################
## Check if there's already a "${DATABASE_NAME}" database present. 
##   If not, create the "${DATABASE_NAME}" database and the requisite db users, 
##           then proceed to invoke the initialize.sql script.
##   If yes, proceed to invoke initialize.sql script only.
###########################################################
SQLINPUTFILE=create_user_and_db
if ! $PSQL -f $SQLINPUTFILE.sql -L log/$SQLINPUTFILE.log; then
  ExitWithError
fi

SQLINPUTFILE=set_users_search_path
if ! $PSQL -f $SQLINPUTFILE.sql -L log/$SQLINPUTFILE.log; then
  ExitWithError
fi

SQLINPUTFILE=initialize
if ! $PSQL -d ${DATABASE_NAME} -f $SQLINPUTFILE.sql -L log/$SQLINPUTFILE.log; then
  ExitWithError
fi

##RdsAdmin=$($PSQL -A -t -c "select usename from pg_user where usename = 'rdsadmin'")
##if [ -n "$RdsAdmin" ]; then
##  echo Amazon RDS environment detected. Re-configuring postgis environment appropriately...
##  SQLINPUTFILE=rds_postgis_setup
##  if ! $PSQL -d ${DATABASE_NAME} -f $SQLINPUTFILE.sql -L log/$SQLINPUTFILE.log; then
##    ExitWithError
##  fi
##fi

STIME=$(date '+%s')

if [ -f data_dump/fbapp.schema ]; then
  echo Restoring fbapp schema. Please enter password for user fishbase
  if ! $RESTORE -d ${DATABASE_NAME} -U fishbase data_dump/fbapp.schema; then 
    ExitWithError
  fi
fi

if [ -f data_dump/slbapp.schema ]; then
  echo Restoring slbapp schema. Please enter password for user fishbase
  if ! $RESTORE -d ${DATABASE_NAME} -U fishbase data_dump/slbapp.schema; then 
    ExitWithError
  fi
fi

ETIME=$(date '+%s')
echo "Schema data restored in $(($ETIME - $STIME)) seconds"

STIME=$(date '+%s')
# Clear previous content of rmv.sql or create anew
echo "vacuum analyze;" > rmv.sql

## Adding foreign keys
cat index_admin.sql >> rmv.sql
cat foreign_key_admin.sql >> rmv.sql

## Adding commands to refresh materialized views
if ! $PSQLFISHBASE -d ${DATABASE_NAME} -f refresh_mv.sql -t >> rmv.sql; then
  ExitWithError
fi

if ! $PSQLFISHBASE -d ${DATABASE_NAME} -f rmv.sql; then
  ExitWithError
fi

ETIME=$(date '+%s')
echo "Vacuuming, Indexing, Foreign Key Creations and Refreshing of Materialized Views completed in $(($ETIME - $STIME)) seconds"

#
# Success: print message and exit with successful return code
#
echo
echo #####
echo Successfully created ${DATABASE_NAME} database!
echo #####
SQLINPUTFILE=
exit 0                 

