CREATE OR REPLACE FUNCTION main.grant_access() RETURNS void AS
$body$
  GRANT USAGE ON SCHEMA main TO web_fb;
  GRANT SELECT,REFERENCES ON ALL TABLES IN SCHEMA main TO web_fb;
  GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA main TO web_fb;
  GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA main TO web_fb;
$body$
LANGUAGE sql
SECURITY DEFINER;

SELECT main.grant_access();
